In [20]:
import numpy as np

araay = np.random.rand(100)
# araay

In [21]:
new_array = araay.reshape(20,5)
# new_array

In [22]:
# X = new_array[:, :4]

In [23]:
# X

In [24]:
# Y = new_array[:, 4:]

In [25]:
target = np.random.randint(0, 2, 20)
target

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0])

In [26]:
# new_array[:, -1] = target.flatten()

In [27]:
# new_array.append(target, axis=0)
new_array = np.hstack((new_array, target[:, None]))
new_array

array([[5.59267221e-01, 6.51641356e-01, 6.92432646e-01, 5.12320956e-01,
        2.31231774e-01, 0.00000000e+00],
       [8.50195087e-01, 5.34868287e-01, 1.12119504e-01, 3.88343430e-02,
        6.43169129e-01, 1.00000000e+00],
       [3.96607802e-01, 7.96811795e-01, 1.04657790e-02, 8.80165689e-01,
        1.66357842e-01, 1.00000000e+00],
       [3.64414614e-02, 9.97085403e-01, 1.52394188e-04, 7.62255870e-01,
        8.75960490e-01, 1.00000000e+00],
       [5.70613288e-01, 4.54200629e-01, 6.02130893e-01, 9.99623206e-01,
        7.29534221e-01, 0.00000000e+00],
       [2.47936334e-01, 9.52009656e-01, 4.15226190e-01, 5.24876611e-01,
        4.52153317e-01, 1.00000000e+00],
       [1.29052905e-01, 9.95365389e-01, 5.97160074e-02, 7.21798346e-01,
        2.00171084e-01, 0.00000000e+00],
       [7.25050898e-01, 2.89381684e-02, 2.29130793e-01, 3.21297693e-01,
        8.09667837e-01, 0.00000000e+00],
       [8.76828763e-01, 5.42917604e-01, 3.83366739e-01, 4.97977819e-01,
        9.07185241e-01, 

In [62]:
X = new_array[:, :-1]
Y = new_array[:, -1]

In [63]:
train_index = int(0.80*len(X))

In [64]:
train_index

16

In [65]:
X_train, y_train = X[:16 :], X[16: :]

In [66]:
len(X_train), len(y_train)

(16, 4)

In [67]:
X_train.shape, y_train.shape

((16, 5), (4, 5))

In [43]:
X_test, y_test = Y[:16 :], Y[16: :]

In [68]:
X_test.shape, y_test.shape

((16,), (4,))

In [71]:
X_test.reshape(16,1)
X_test

array([0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1.])

In [72]:
len(X_test), (len(y_test))

(16, 4)

In [73]:
X_test.shape

(16,)

In [74]:
# X_train, X_test = X[:split_index], X[split_index:]
# y_train, y_test = y[:split_index], y[split_index:]
y_train.shape

(4, 5)

In [75]:
def euclidean_distance(x1, x2):
  return np.sqrt(np.sum((x1-x2)**2))

In [76]:
def knn(X_train, y_train, X_test, k):
    y_pred = []

    for test_point in X_test:
        distances = [euclidean_distance(test_point, train_point) for train_point in X_train]
        k_nearest_indices = np.argsort(distances)[:k]
        k_nearest_labels = [y_train[i] for i in k_nearest_indices]
        # Predict the label based on the majority class among the k-nearest neighbors
        pred_label = max(set(k_nearest_labels), key=k_nearest_labels.count)
        y_pred.append(pred_label)

    return np.array(y_pred)

In [82]:
def knn_classify(x_train, y_train, x_test, k):
    distances = np.linalg.norm(x_train - x_test, axis=1)

  # Find the K most similar training data points to each test data point.
    nearest_neighbors = np.argsort(distances)[:, :k]

  # Predict the label of each test data point by taking the majority vote of the labels of the K most similar training data points.
    predicted_labels = y_train[nearest_neighbors]
    mode, _ = np.unique(predicted_labels, axis=1, return_counts=True)
    return mode

In [83]:
# Apply the KNN algorithm with k=3
k = 3
# y_pred = knn(X_train, y_train, X_test, k)
y_pred1 = knn_classify(X_train, y_train, X_test, k) 
# Calculate accuracy
accuracy = np.mean(y_pred == y_test)
accuracy = np.mean(y_pred1 == y_test)
print("Accuracy:", accuracy)
print("Accuracy1:", accuracy)

ValueError: cannot reshape array of size 16 into shape (16,5)