In [1]:
import torch
print(torch.__version__)

2.0.1+cu117


In [2]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
scalar.ndim

0

In [4]:
#get tensor back as py int
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MAtrix 
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

matrix.shape

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3, 4],
                      [3,6,7,4],
                      [4,5,6,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 7, 4],
         [4, 5, 6, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

In [15]:
TENSOR[0, 0]

tensor([1, 2, 3, 4])

In [16]:
#Random Tensors
random_t = torch.rand(3, 4)
random_t

tensor([[0.3366, 0.2062, 0.3095, 0.9270],
        [0.2888, 0.2009, 0.1999, 0.0301],
        [0.8339, 0.7349, 0.0047, 0.8267]])

In [17]:
random_t.ndim

2

In [18]:
random_t.shape

torch.Size([3, 4])

In [19]:
#Creaye a random tensor similar to image

rand_img_tensor = torch.rand(size = (224, 224, 3))

rand_img_tensor.shape, rand_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(3,3)

tensor([[0.4919, 0.4665, 0.9246],
        [0.6604, 0.7583, 0.1027],
        [0.7084, 0.2901, 0.0677]])

In [21]:
# zeros and ones
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
### Crearing a range of tensors

one_to_ten = torch.arange(start = 0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Tensors Data Types
# Float32 tensor

float_32_ten = torch.tensor([3.0, 4.0, 5.5], dtype=None, device = "cpu", requires_grad=False)
float_32_tenf

tensor([3.0000, 4.0000, 5.5000])

In [26]:
float_32_ten.dtype

torch.float32

In [27]:
float_16_num = float_32_ten.type(torch.float16)

In [28]:
float_16_num

tensor([3.0000, 4.0000, 5.5000], dtype=torch.float16)

In [29]:
float_16_num * float_32_ten

tensor([ 9.0000, 16.0000, 30.2500])

In [30]:
int_32_t = torch.tensor([3,6,9], dtype=torch.int32)

In [31]:
float_16_num * float_32_ten * int_32_t

tensor([ 27.0000,  96.0000, 272.2500])

In [32]:

# Getting Information From Tensors

Some_tensor = torch.rand(3,4)
Some_tensor

tensor([[0.9734, 0.8418, 0.5386, 0.0364],
        [0.8439, 0.0202, 0.4624, 0.4452],
        [0.2052, 0.4003, 0.6318, 0.3884]])

In [33]:
# Find Out details about some tensor

print(Some_tensor)
print(f"Shape of tensor is: {Some_tensor.shape}")
print(f"data type of tensor is: {Some_tensor.dtype}")
print(f"Device tensor is On : {Some_tensor.device}")

tensor([[0.9734, 0.8418, 0.5386, 0.0364],
        [0.8439, 0.0202, 0.4624, 0.4452],
        [0.2052, 0.4003, 0.6318, 0.3884]])
Shape of tensor is: torch.Size([3, 4])
data type of tensor is: torch.float32
Device tensor is On : cpu


In [34]:
#Manipulating Tensors (Tensors Operations)

tensor = torch.tensor([1,2,3])

tensor + 10


tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
#Try out pytorch in -built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [40]:
#Elementwise Multiplication
print(tensor, "*" , tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [41]:
%%time
1*1 + 2*2 + 3*3

CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 19.1 µs


14

In [42]:

%%time

torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 2.02 ms, total: 2.02 ms
Wall time: 3.44 ms


tensor(14)

In [43]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.62 ms, sys: 0 ns, total: 2.62 ms
Wall time: 1.82 ms


In [44]:
t1 = torch.tensor([[1,2,3],
                  [3,4,5]])
t2 = torch.tensor([[1,2],
                  [3,4],
                 [5,6]])

In [45]:
torch.matmul(t1, t2)

tensor([[22, 28],
        [40, 52]])

In [46]:
# Shape Errors 
# 1 the inner dimensions must match
#

torch.matmul(torch.rand(3,2), torch.rand(2,3))



tensor([[0.1398, 0.1081, 0.0537],
        [0.7070, 0.4130, 0.2517],
        [0.5262, 0.2374, 0.1770]])

In [47]:
torch.matmul(torch.rand(2,4), torch.rand(4,2))


tensor([[1.0091, 1.0442],
        [1.1161, 0.4032]])

In [48]:
# SHAPES FOR MATRIX MULTIPLICATION
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [49]:
## Finding the Min Max, mean, sum etc

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [51]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [52]:
x.type(torch.float32).mean()

tensor(45.)

In [53]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [54]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [55]:
#positional min max

x.argmin()

tensor(0)

In [56]:
x.argmax()

tensor(9)

In [57]:
#reshaping, resizing and stacking the tensors
x.shape


torch.Size([10])

In [58]:
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [71]:
x = torch.arange(1.0, 11.0)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [66]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [67]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [79]:
x_reshaped = torch.transpose(x, 0, -1)
x_reshaped

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [72]:
x.shape

torch.Size([10])

In [74]:
x_squeezed = x.squeeze()
x_squeezed.shape

torch.Size([10])

In [85]:
x_unsqueezed = x.unsqueeze(dim=1)

In [86]:
x_unsqueezed.shape

torch.Size([10, 1])

In [87]:
x_unsqueezed

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [88]:
x_squeezed = x_unsqueezed.squeeze()
x_squeezed.shape

torch.Size([10])

In [89]:
x_squeezed

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [92]:
x = torch.randn(2, 3, 5)
print(x)
print(x.size())
# torch.Size([2, 3, 5])
torch.permute(x, (2, 0, 1)).size()

tensor([[[-0.7461, -0.5700,  1.4819, -1.1422, -0.9990],
         [-0.3151, -0.6111, -0.0187,  1.1856, -1.1416],
         [-1.8353, -0.3916,  0.6936,  0.3526, -0.0643]],

        [[ 0.8471, -0.5732,  1.7415, -0.3448, -1.7688],
         [ 1.1238, -0.8614,  1.5559,  0.6423, -0.5415],
         [ 2.6856, -0.5286, -0.4342, -0.8303, -0.7058]]])
torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [95]:
x_orig = torch.rand(size=(224, 224, 3)) # height , width and channels

# permute
x_permuted = x_orig.permute(2,0,1)
print(f"Original image is : {x_orig.shape}")
print(f"\n permuted image is : {x_permuted.shape}")

Original image is : torch.Size([224, 224, 3])

 permuted image is : torch.Size([3, 224, 224])


In [98]:
## indexing and selecting data from tensors:


import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
#l3ts index on this tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0][0]

tensor([1, 2, 3])

In [103]:
#last dimesnsion
x[0][0][0]

tensor(1)

In [109]:
x[0:, :1, 0]

tensor([[1]])

In [110]:
x[0][2][2]

tensor(9)

In [112]:
x[:, 0]

tensor([[1, 2, 3]])

In [113]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [114]:
x[:, 1, 1]

tensor([5])

In [115]:
x[0, 0, :]

tensor([1, 2, 3])

In [116]:
x[0,2,2]

tensor(9)

In [117]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [118]:
##pytorch tensors and numpy

import numpy as np


In [119]:
a = np.arange(1,10)

In [120]:
b = torch.from_numpy(a)

In [122]:
a, b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [123]:
a.dtype, b.dtype

(dtype('int64'), torch.int64)

In [125]:
torch.arange(1.0, 10.0).dtype

torch.float32

In [130]:
#tensir to numpy array

tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [131]:
numpy_tensor.dtype

dtype('float32')

In [134]:
tensor = tensor + 1
tensor, numpy_tensor


(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
##REproduceablility 

In [137]:
RDA = torch.rand(3,3)
RDB = torch.rand(3,3)
RDA, RDB

(tensor([[0.3904, 0.0934, 0.4017],
         [0.1675, 0.7908, 0.5636],
         [0.8516, 0.3295, 0.2571]]),
 tensor([[0.2700, 0.0573, 0.4165],
         [0.6450, 0.2813, 0.8727],
         [0.0463, 0.9196, 0.3358]]))

In [138]:
RDA == RDB

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [143]:
#lets make some random and reproduceable tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)


RDC = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
RDD = torch.rand(3,4)

RDC, RDD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [144]:
RDC == RDD

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [145]:
# Running Tensors and Pytorch Ojects:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [150]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [151]:
device

'cpu'

In [152]:
a = torch.ones(7, device=device)

In [154]:
a.device

device(type='cpu')

In [155]:
a.to(device)

tensor([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
## 